### ISSUE TITLE
Problems to use

### ISSUE THREAD

**Issue by Pit80333** [Red5d/edlkit#1]
The scripts look promissing for me, just what I was looking for.
I just have very little knowledge about python and I failed to use your scripts (tried Ubuntu 15.04 and Arch). 
I always get python errors. Looking in the source code it seems - for me - like a mixture for Python 2.7 and 3.x, e.g. print statements with / without paranthesis. In edltweak-gui.py you use "tkinter" (lowercase t) which indicates Python 3.x. 
I get the following error:
python3 ./edltweak-gui.py /media//Zug.ts Zug.edl 
Traceback (most recent call last):
  File "./edltweak-gui.py", line 3, in <module>
    import os, sys, curses, edl, socket, subprocess, time
  File "/home/public/edlkit/edlkit-master/edl.py", line 7
    print self.edlfile.read()
             ^
SyntaxError: invalid syntax

What Linux environment and which Python version should I use?

**Comment by Red5d** [comment]
Yes, this started out as a python 2.7 project, and I'm now shifting it to Python 3 since adding the edltweak-gui.py script (which uses Python3 TKinter for the gui).

Those parameters you're using don't look quite right... What's a .ts file? And is that an extra "/" in "/media//Zug.ts"?

**Comment by Red5d** [comment]
Ok, I tried using it myself a few minutes ago and had the same error. I've fixed the syntax error in edl.py to use Python 3 syntax. "git pull" and try again.

**Comment by Pit80333** [comment]
Thanks. I just have had time for a short test. It is now working (Arch Linux, Python 3.5)! As I use a HiDPI Screen (Yoga 3 Pro) it is a little bit harde to read, but never mind. It is a helpfull tool to deal with edl files,
A .ts is a video file (MPEG Transport Stream, see e.g. https://en.wikipedia.org/wiki/MPEG_transport_stream). I believe this is the usual format when you record DVB-S  or DVB-C or DVB-T streams. I do in generall use tvheadend to record TV programs.

**Comment by Red5d** [comment]
Ok, cool. Glad it's useful! I have plans for extending it to integrate with some of the other scripts as well (edledit, edlcreate) so those can be used from the GUI too. Suggestions/ideas are certainly welcome.
