### ISSUE TITLE
Mac localhost isn't starting up in edlcreate.py or .._timer.py

### ISSUE THREAD

**Issue by JonasIsLive** [Red5d/edlkit#2]
Hey, 
thank you so much for creating thing!! it is absolutely a life saver, if i can get it up and running! 

Im currently struggling to get the socket to connect to the vlc localhost. (im on mac, so i assume thats why its behaving weird, but i dont have a linux)

when I run this command:
python3 edlcreate.py "moviefile.MP4" "edltest.edl"

I get the printout:
Starting VLC...

But it runs forever and nothing is ever popping up. Not even if I go the the localhost url or anything.

If I then cancel with ctrl+c then it points me to the following code snippet:
if testConn > 0:
    subprocess.Popen(["vlc","-q","--extraintf","rc","--rc-host","localhost:1200"], shell=True, stdout=DEVNULL, stderr=subprocess.STDOUT)
    print("Starting VLC...")
    while testConn > 0:
        testConn = vlc.connect_ex(('127.0.0.1', 1200))
        time.sleep(0.5)

this is the output form the ctrl+c:
^CTraceback (most recent call last):
  File "edlcreate.py", line 27, in <module>
    time.sleep(0.5)
KeyboardInterrupt

Please help me get this up and running, it could really save me rn..

**Comment by Red5d** [comment]
Do you have VLC installed? And if so, does running this command manually open VLC?
`vlc -q --extraintf rc --rc-host localhost:1200`

**Comment by JonasIsLive** [comment]
I feel like an absolute tool... I had vlc installed, but your comment got me thinking and low and behold.. 

alias vlc='/Applications/VLC.app/Contents/MacOS/VLC'

fixed it.. I hadn't setup the path variable vlc correctly...

thank you so very much for the speedy response!! 
and apologies for wasting your time..
